
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ttu.idu0080.myclient;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-05-14T10:54:39.195+03:00
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "OrderServiceService",
                      portName = "OrderServicePort",
                      targetNamespace = "http://server.order.idu0080.ttu/",
                      wsdlLocation = "http://localhost:8080/OrderService/services/OrderServicePort?wsdl",
                      endpointInterface = "ttu.idu0080.myclient.OrderService")
                      
public class OrderServiceImpl implements OrderService {

    private static final Logger LOG = Logger.getLogger(OrderServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see ttu.idu0080.myclient.OrderService#getOrdersByCustomerId(int  customerId )*
     */
    public java.util.List<ttu.idu0080.myclient.Order> getOrdersByCustomerId(int customerId) { 
        LOG.info("Executing operation getOrdersByCustomerId");
        System.out.println(customerId);
        try {
            java.util.List<ttu.idu0080.myclient.Order> _return = new java.util.ArrayList<ttu.idu0080.myclient.Order>();
            ttu.idu0080.myclient.Order _returnVal1 = new ttu.idu0080.myclient.Order();
            ttu.idu0080.myclient.Customer _returnVal1Customer = new ttu.idu0080.myclient.Customer();
            java.util.List<ttu.idu0080.myclient.Address> _returnVal1CustomerAddresses = new java.util.ArrayList<ttu.idu0080.myclient.Address>();
            _returnVal1Customer.getAddresses().addAll(_returnVal1CustomerAddresses);
            _returnVal1Customer.setCustomer(-639479228);
            _returnVal1Customer.setFirstName("FirstName-1575641186");
            _returnVal1Customer.setLastName("LastName-956114506");
            _returnVal1.setCustomer(_returnVal1Customer);
            _returnVal1.setOrderId(1692000235);
            java.util.List<ttu.idu0080.myclient.OrderProduct> _returnVal1OrderProducts = new java.util.ArrayList<ttu.idu0080.myclient.OrderProduct>();
            ttu.idu0080.myclient.OrderProduct _returnVal1OrderProductsVal1 = new ttu.idu0080.myclient.OrderProduct();
            _returnVal1OrderProductsVal1.setOrderProduct(1281088533);
            _returnVal1OrderProductsVal1.setPrice(0.9084002f);
            _returnVal1OrderProductsVal1.setPriceTotal(0.33755577f);
            _returnVal1OrderProductsVal1.setProductCount(-1832509843);
            _returnVal1OrderProductsVal1.setProductName("ProductName-1224942120");
            _returnVal1OrderProducts.add(_returnVal1OrderProductsVal1);
            _returnVal1.getOrderProducts().addAll(_returnVal1OrderProducts);
            _returnVal1.setPriceTotal(0.84353405f);
            ttu.idu0080.myclient.Seller _returnVal1Seller = new ttu.idu0080.myclient.Seller();
            java.util.List<ttu.idu0080.myclient.EntAddress> _returnVal1SellerAddresses = new java.util.ArrayList<ttu.idu0080.myclient.EntAddress>();
            _returnVal1Seller.getAddresses().addAll(_returnVal1SellerAddresses);
            _returnVal1Seller.setEnterprise(1164968936);
            _returnVal1Seller.setName("Name-1887126884");
            _returnVal1.setSeller(_returnVal1Seller);
            ttu.idu0080.myclient.Address _returnVal1ShippingAddress = new ttu.idu0080.myclient.Address();
            _returnVal1ShippingAddress.setAddress(1049477527);
            _returnVal1ShippingAddress.setCountry("Country348385307");
            _returnVal1ShippingAddress.setCounty("County1413882727");
            _returnVal1ShippingAddress.setStreetAddress("StreetAddress1159238693");
            _returnVal1ShippingAddress.setTownVillage("TownVillage-626179897");
            _returnVal1ShippingAddress.setZipcode("Zipcode1874143548");
            _returnVal1.setShippingAddress(_returnVal1ShippingAddress);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.myclient.OrderService#getAllOrders(*
     */
    public java.util.List<ttu.idu0080.myclient.Order> getAllOrders() { 
        LOG.info("Executing operation getAllOrders");
        try {
            java.util.List<ttu.idu0080.myclient.Order> _return = new java.util.ArrayList<ttu.idu0080.myclient.Order>();
            ttu.idu0080.myclient.Order _returnVal1 = new ttu.idu0080.myclient.Order();
            ttu.idu0080.myclient.Customer _returnVal1Customer = new ttu.idu0080.myclient.Customer();
            java.util.List<ttu.idu0080.myclient.Address> _returnVal1CustomerAddresses = new java.util.ArrayList<ttu.idu0080.myclient.Address>();
            _returnVal1Customer.getAddresses().addAll(_returnVal1CustomerAddresses);
            _returnVal1Customer.setCustomer(808876935);
            _returnVal1Customer.setFirstName("FirstName-718733207");
            _returnVal1Customer.setLastName("LastName-430437754");
            _returnVal1.setCustomer(_returnVal1Customer);
            _returnVal1.setOrderId(-1921196933);
            java.util.List<ttu.idu0080.myclient.OrderProduct> _returnVal1OrderProducts = new java.util.ArrayList<ttu.idu0080.myclient.OrderProduct>();
            ttu.idu0080.myclient.OrderProduct _returnVal1OrderProductsVal1 = new ttu.idu0080.myclient.OrderProduct();
            _returnVal1OrderProductsVal1.setOrderProduct(826644672);
            _returnVal1OrderProductsVal1.setPrice(0.33933115f);
            _returnVal1OrderProductsVal1.setPriceTotal(0.24728453f);
            _returnVal1OrderProductsVal1.setProductCount(-1140761780);
            _returnVal1OrderProductsVal1.setProductName("ProductName1895668185");
            _returnVal1OrderProducts.add(_returnVal1OrderProductsVal1);
            _returnVal1.getOrderProducts().addAll(_returnVal1OrderProducts);
            _returnVal1.setPriceTotal(0.783725f);
            ttu.idu0080.myclient.Seller _returnVal1Seller = new ttu.idu0080.myclient.Seller();
            java.util.List<ttu.idu0080.myclient.EntAddress> _returnVal1SellerAddresses = new java.util.ArrayList<ttu.idu0080.myclient.EntAddress>();
            _returnVal1Seller.getAddresses().addAll(_returnVal1SellerAddresses);
            _returnVal1Seller.setEnterprise(1806111203);
            _returnVal1Seller.setName("Name-390021472");
            _returnVal1.setSeller(_returnVal1Seller);
            ttu.idu0080.myclient.Address _returnVal1ShippingAddress = new ttu.idu0080.myclient.Address();
            _returnVal1ShippingAddress.setAddress(-594288060);
            _returnVal1ShippingAddress.setCountry("Country-727606928");
            _returnVal1ShippingAddress.setCounty("County-1178538494");
            _returnVal1ShippingAddress.setStreetAddress("StreetAddress502568862");
            _returnVal1ShippingAddress.setTownVillage("TownVillage-1949495608");
            _returnVal1ShippingAddress.setZipcode("Zipcode1557665690");
            _returnVal1.setShippingAddress(_returnVal1ShippingAddress);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.myclient.OrderService#getOrdersByOrderId(int  orderId )*
     */
    public ttu.idu0080.myclient.Order getOrdersByOrderId(int orderId) { 
        LOG.info("Executing operation getOrdersByOrderId");
        System.out.println(orderId);
        try {
            ttu.idu0080.myclient.Order _return = new ttu.idu0080.myclient.Order();
            ttu.idu0080.myclient.Customer _returnCustomer = new ttu.idu0080.myclient.Customer();
            java.util.List<ttu.idu0080.myclient.Address> _returnCustomerAddresses = new java.util.ArrayList<ttu.idu0080.myclient.Address>();
            ttu.idu0080.myclient.Address _returnCustomerAddressesVal1 = new ttu.idu0080.myclient.Address();
            _returnCustomerAddressesVal1.setAddress(-657644552);
            _returnCustomerAddressesVal1.setCountry("Country460552082");
            _returnCustomerAddressesVal1.setCounty("County1712918624");
            _returnCustomerAddressesVal1.setStreetAddress("StreetAddress-1973433981");
            _returnCustomerAddressesVal1.setTownVillage("TownVillage266658300");
            _returnCustomerAddressesVal1.setZipcode("Zipcode-116489435");
            _returnCustomerAddresses.add(_returnCustomerAddressesVal1);
            _returnCustomer.getAddresses().addAll(_returnCustomerAddresses);
            _returnCustomer.setCustomer(580620643);
            _returnCustomer.setFirstName("FirstName-787297743");
            _returnCustomer.setLastName("LastName-756161843");
            _return.setCustomer(_returnCustomer);
            _return.setOrderId(559449294);
            java.util.List<ttu.idu0080.myclient.OrderProduct> _returnOrderProducts = new java.util.ArrayList<ttu.idu0080.myclient.OrderProduct>();
            ttu.idu0080.myclient.OrderProduct _returnOrderProductsVal1 = new ttu.idu0080.myclient.OrderProduct();
            _returnOrderProductsVal1.setOrderProduct(-2072835868);
            _returnOrderProductsVal1.setPrice(0.05240339f);
            _returnOrderProductsVal1.setPriceTotal(0.8438001f);
            _returnOrderProductsVal1.setProductCount(-257478008);
            _returnOrderProductsVal1.setProductName("ProductName-1932320677");
            _returnOrderProducts.add(_returnOrderProductsVal1);
            _return.getOrderProducts().addAll(_returnOrderProducts);
            _return.setPriceTotal(0.48531002f);
            ttu.idu0080.myclient.Seller _returnSeller = new ttu.idu0080.myclient.Seller();
            java.util.List<ttu.idu0080.myclient.EntAddress> _returnSellerAddresses = new java.util.ArrayList<ttu.idu0080.myclient.EntAddress>();
            ttu.idu0080.myclient.EntAddress _returnSellerAddressesVal1 = new ttu.idu0080.myclient.EntAddress();
            _returnSellerAddressesVal1.setAddress(432126643);
            _returnSellerAddressesVal1.setCountry("Country1677105861");
            _returnSellerAddressesVal1.setCounty("County1319980932");
            _returnSellerAddressesVal1.setStreetAddress("StreetAddress-1010199849");
            _returnSellerAddressesVal1.setTownVillage("TownVillage50737980");
            _returnSellerAddressesVal1.setZipcode("Zipcode1096936610");
            _returnSellerAddresses.add(_returnSellerAddressesVal1);
            _returnSeller.getAddresses().addAll(_returnSellerAddresses);
            _returnSeller.setEnterprise(1441583750);
            _returnSeller.setName("Name-393205550");
            _return.setSeller(_returnSeller);
            ttu.idu0080.myclient.Address _returnShippingAddress = new ttu.idu0080.myclient.Address();
            _returnShippingAddress.setAddress(-1146919235);
            _returnShippingAddress.setCountry("Country795086683");
            _returnShippingAddress.setCounty("County-856072616");
            _returnShippingAddress.setStreetAddress("StreetAddress-1203913328");
            _returnShippingAddress.setTownVillage("TownVillage-1685478457");
            _returnShippingAddress.setZipcode("Zipcode742767872");
            _return.setShippingAddress(_returnShippingAddress);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.myclient.OrderService#getOrdersByShippingAddress(java.lang.String  country ,)java.lang.String  county )*
     */
    public java.util.List<ttu.idu0080.myclient.Order> getOrdersByShippingAddress(java.lang.String country,java.lang.String county) { 
        LOG.info("Executing operation getOrdersByShippingAddress");
        System.out.println(country);
        System.out.println(county);
        try {
            java.util.List<ttu.idu0080.myclient.Order> _return = new java.util.ArrayList<ttu.idu0080.myclient.Order>();
            ttu.idu0080.myclient.Order _returnVal1 = new ttu.idu0080.myclient.Order();
            ttu.idu0080.myclient.Customer _returnVal1Customer = new ttu.idu0080.myclient.Customer();
            java.util.List<ttu.idu0080.myclient.Address> _returnVal1CustomerAddresses = new java.util.ArrayList<ttu.idu0080.myclient.Address>();
            _returnVal1Customer.getAddresses().addAll(_returnVal1CustomerAddresses);
            _returnVal1Customer.setCustomer(-125421728);
            _returnVal1Customer.setFirstName("FirstName-1503740280");
            _returnVal1Customer.setLastName("LastName-686193342");
            _returnVal1.setCustomer(_returnVal1Customer);
            _returnVal1.setOrderId(-1689906072);
            java.util.List<ttu.idu0080.myclient.OrderProduct> _returnVal1OrderProducts = new java.util.ArrayList<ttu.idu0080.myclient.OrderProduct>();
            ttu.idu0080.myclient.OrderProduct _returnVal1OrderProductsVal1 = new ttu.idu0080.myclient.OrderProduct();
            _returnVal1OrderProductsVal1.setOrderProduct(1776914012);
            _returnVal1OrderProductsVal1.setPrice(0.07505363f);
            _returnVal1OrderProductsVal1.setPriceTotal(0.70352095f);
            _returnVal1OrderProductsVal1.setProductCount(-1268394394);
            _returnVal1OrderProductsVal1.setProductName("ProductName-1248704635");
            _returnVal1OrderProducts.add(_returnVal1OrderProductsVal1);
            _returnVal1.getOrderProducts().addAll(_returnVal1OrderProducts);
            _returnVal1.setPriceTotal(0.6015694f);
            ttu.idu0080.myclient.Seller _returnVal1Seller = new ttu.idu0080.myclient.Seller();
            java.util.List<ttu.idu0080.myclient.EntAddress> _returnVal1SellerAddresses = new java.util.ArrayList<ttu.idu0080.myclient.EntAddress>();
            _returnVal1Seller.getAddresses().addAll(_returnVal1SellerAddresses);
            _returnVal1Seller.setEnterprise(-145867683);
            _returnVal1Seller.setName("Name227328570");
            _returnVal1.setSeller(_returnVal1Seller);
            ttu.idu0080.myclient.Address _returnVal1ShippingAddress = new ttu.idu0080.myclient.Address();
            _returnVal1ShippingAddress.setAddress(1005621233);
            _returnVal1ShippingAddress.setCountry("Country39679517");
            _returnVal1ShippingAddress.setCounty("County-1221510014");
            _returnVal1ShippingAddress.setStreetAddress("StreetAddress1665385802");
            _returnVal1ShippingAddress.setTownVillage("TownVillage-108534472");
            _returnVal1ShippingAddress.setZipcode("Zipcode1309706655");
            _returnVal1.setShippingAddress(_returnVal1ShippingAddress);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.myclient.OrderService#getOrdersByCustomerLastName(java.lang.String  lastName )*
     */
    public java.util.List<ttu.idu0080.myclient.Order> getOrdersByCustomerLastName(java.lang.String lastName) { 
        LOG.info("Executing operation getOrdersByCustomerLastName");
        System.out.println(lastName);
        try {
            java.util.List<ttu.idu0080.myclient.Order> _return = new java.util.ArrayList<ttu.idu0080.myclient.Order>();
            ttu.idu0080.myclient.Order _returnVal1 = new ttu.idu0080.myclient.Order();
            ttu.idu0080.myclient.Customer _returnVal1Customer = new ttu.idu0080.myclient.Customer();
            java.util.List<ttu.idu0080.myclient.Address> _returnVal1CustomerAddresses = new java.util.ArrayList<ttu.idu0080.myclient.Address>();
            _returnVal1Customer.getAddresses().addAll(_returnVal1CustomerAddresses);
            _returnVal1Customer.setCustomer(-1792610707);
            _returnVal1Customer.setFirstName("FirstName-474615278");
            _returnVal1Customer.setLastName("LastName-1792576678");
            _returnVal1.setCustomer(_returnVal1Customer);
            _returnVal1.setOrderId(-1316447390);
            java.util.List<ttu.idu0080.myclient.OrderProduct> _returnVal1OrderProducts = new java.util.ArrayList<ttu.idu0080.myclient.OrderProduct>();
            ttu.idu0080.myclient.OrderProduct _returnVal1OrderProductsVal1 = new ttu.idu0080.myclient.OrderProduct();
            _returnVal1OrderProductsVal1.setOrderProduct(1271255697);
            _returnVal1OrderProductsVal1.setPrice(0.38802254f);
            _returnVal1OrderProductsVal1.setPriceTotal(0.3581531f);
            _returnVal1OrderProductsVal1.setProductCount(8263203);
            _returnVal1OrderProductsVal1.setProductName("ProductName183369365");
            _returnVal1OrderProducts.add(_returnVal1OrderProductsVal1);
            _returnVal1.getOrderProducts().addAll(_returnVal1OrderProducts);
            _returnVal1.setPriceTotal(0.86964273f);
            ttu.idu0080.myclient.Seller _returnVal1Seller = new ttu.idu0080.myclient.Seller();
            java.util.List<ttu.idu0080.myclient.EntAddress> _returnVal1SellerAddresses = new java.util.ArrayList<ttu.idu0080.myclient.EntAddress>();
            _returnVal1Seller.getAddresses().addAll(_returnVal1SellerAddresses);
            _returnVal1Seller.setEnterprise(1167868224);
            _returnVal1Seller.setName("Name-1187617904");
            _returnVal1.setSeller(_returnVal1Seller);
            ttu.idu0080.myclient.Address _returnVal1ShippingAddress = new ttu.idu0080.myclient.Address();
            _returnVal1ShippingAddress.setAddress(-914631589);
            _returnVal1ShippingAddress.setCountry("Country56161516");
            _returnVal1ShippingAddress.setCounty("County-436939387");
            _returnVal1ShippingAddress.setStreetAddress("StreetAddress-1238998500");
            _returnVal1ShippingAddress.setTownVillage("TownVillage1421911357");
            _returnVal1ShippingAddress.setZipcode("Zipcode-1539518315");
            _returnVal1.setShippingAddress(_returnVal1ShippingAddress);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
