package ttu.idu0080.orderservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-05-15T08:09:19.991+03:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://server.order.idu0080.ttu/", name = "OrderService")
@XmlSeeAlso({ObjectFactory.class})
public interface OrderService {

    @WebMethod
    @Action(input = "http://server.order.idu0080.ttu/OrderService/getOrdersByCustomerIdRequest", output = "http://server.order.idu0080.ttu/OrderService/getOrdersByCustomerIdResponse")
    @RequestWrapper(localName = "getOrdersByCustomerId", targetNamespace = "http://server.order.idu0080.ttu/", className = "ttu.idu0080.orderservice.GetOrdersByCustomerId")
    @ResponseWrapper(localName = "getOrdersByCustomerIdResponse", targetNamespace = "http://server.order.idu0080.ttu/", className = "ttu.idu0080.orderservice.GetOrdersByCustomerIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ttu.idu0080.orderservice.Order> getOrdersByCustomerId(
        @WebParam(name = "customer_id", targetNamespace = "")
        int customerId
    );

    @WebMethod
    @Action(input = "http://server.order.idu0080.ttu/OrderService/getAllOrdersRequest", output = "http://server.order.idu0080.ttu/OrderService/getAllOrdersResponse")
    @RequestWrapper(localName = "getAllOrders", targetNamespace = "http://server.order.idu0080.ttu/", className = "ttu.idu0080.orderservice.GetAllOrders")
    @ResponseWrapper(localName = "getAllOrdersResponse", targetNamespace = "http://server.order.idu0080.ttu/", className = "ttu.idu0080.orderservice.GetAllOrdersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ttu.idu0080.orderservice.Order> getAllOrders();

    @WebMethod
    @Action(input = "http://server.order.idu0080.ttu/OrderService/getOrdersByOrderIdRequest", output = "http://server.order.idu0080.ttu/OrderService/getOrdersByOrderIdResponse")
    @RequestWrapper(localName = "getOrdersByOrderId", targetNamespace = "http://server.order.idu0080.ttu/", className = "ttu.idu0080.orderservice.GetOrdersByOrderId")
    @ResponseWrapper(localName = "getOrdersByOrderIdResponse", targetNamespace = "http://server.order.idu0080.ttu/", className = "ttu.idu0080.orderservice.GetOrdersByOrderIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ttu.idu0080.orderservice.Order getOrdersByOrderId(
        @WebParam(name = "order_id", targetNamespace = "")
        int orderId
    );

    @WebMethod
    @Action(input = "http://server.order.idu0080.ttu/CourierService/getAllCouriersRequest", output = "http://server.order.idu0080.ttu/CourierService/getAllCouriersResponse")
    @RequestWrapper(localName = "getAllCouriers", targetNamespace = "http://server.order.idu0080.ttu/", className = "ttu.idu0080.orderservice.GetAllCouriers")
    @ResponseWrapper(localName = "getAllCouriersResponse", targetNamespace = "http://server.order.idu0080.ttu/", className = "ttu.idu0080.orderservice.GetAllCouriersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ttu.idu0080.orderservice.Courier> getAllCouriers();

    @WebMethod
    @Action(input = "http://server.order.idu0080.ttu/CourierService/getCourierByIdRequest", output = "http://server.order.idu0080.ttu/CourierService/getCourierByIdResponse")
    @RequestWrapper(localName = "getCourierById", targetNamespace = "http://server.order.idu0080.ttu/", className = "ttu.idu0080.orderservice.GetCourierById")
    @ResponseWrapper(localName = "getCourierByIdResponse", targetNamespace = "http://server.order.idu0080.ttu/", className = "ttu.idu0080.orderservice.GetCourierByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ttu.idu0080.orderservice.Courier getCourierById(
        @WebParam(name = "courier_id", targetNamespace = "")
        int courierId
    );

    @WebMethod
    @Action(input = "http://server.order.idu0080.ttu/ProductService/getAllProductsRequest", output = "http://server.order.idu0080.ttu/ProductService/getAllProductsResponse")
    @RequestWrapper(localName = "getAllProducts", targetNamespace = "http://server.order.idu0080.ttu/", className = "ttu.idu0080.orderservice.GetAllProducts")
    @ResponseWrapper(localName = "getAllProductsResponse", targetNamespace = "http://server.order.idu0080.ttu/", className = "ttu.idu0080.orderservice.GetAllProductsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ttu.idu0080.orderservice.Product> getAllProducts();
}
