
package ttu.idu0080.orderservice;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-05-15T08:09:20+03:00
 * Generated source version: 2.7.18
 * 
 */
 
public class OrderService_OrderServicePort_Server{

    protected OrderService_OrderServicePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new OrderServiceImpl();
        String address = "http://localmachine:8080/orderservice/orders";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new OrderService_OrderServicePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
