package ttu.idu0080.myclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-05-14T11:44:35.554+03:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://transport.idu0080.ttu/", name = "TransportService")
@XmlSeeAlso({ObjectFactory.class})
public interface TransportService {

    @WebMethod
    @RequestWrapper(localName = "getCourierList", targetNamespace = "http://transport.idu0080.ttu/", className = "ttu.idu0080.myclient.GetCourierList")
    @ResponseWrapper(localName = "getCourierListResponse", targetNamespace = "http://transport.idu0080.ttu/", className = "ttu.idu0080.myclient.GetCourierListResponse")
    @WebResult(name = "couriers", targetNamespace = "")
    public java.util.List<ttu.idu0080.myclient.Courierdata> getCourierList();

    @WebMethod
    @RequestWrapper(localName = "getCourierOffer", targetNamespace = "http://transport.idu0080.ttu/", className = "ttu.idu0080.myclient.GetCourierOffer")
    @ResponseWrapper(localName = "getCourierOfferResponse", targetNamespace = "http://transport.idu0080.ttu/", className = "ttu.idu0080.myclient.GetCourierOfferResponse")
    @WebResult(name = "offer", targetNamespace = "")
    public ttu.idu0080.myclient.Offerresponse getCourierOffer(
        @WebParam(name = "orderid", targetNamespace = "")
        int orderid
    );

    @WebMethod
    @RequestWrapper(localName = "setOrderTransport", targetNamespace = "http://transport.idu0080.ttu/", className = "ttu.idu0080.myclient.SetOrderTransport")
    @ResponseWrapper(localName = "setOrderTransportResponse", targetNamespace = "http://transport.idu0080.ttu/", className = "ttu.idu0080.myclient.SetOrderTransportResponse")
    @WebResult(name = "transportid", targetNamespace = "")
    public java.lang.String setOrderTransport(
        @WebParam(name = "offerid", targetNamespace = "")
        java.lang.String offerid
    );
}
