
package ttu.idu0080.orderservice.couriers;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-05-13T14:33:23.696+03:00
 * Generated source version: 2.7.18
 * 
 */
 
public class CourierService_CourierServicePort_Server{

    protected CourierService_CourierServicePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new CourierServiceImpl();
        String address = "http://loclamachine:8080/orderservice/couriers";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new CourierService_CourierServicePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
