
package ttu.idu0080.transport;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-05-15T08:26:47.657+03:00
 * Generated source version: 2.7.18
 * 
 */
 
public class TransportService_TransportServicePort_Server{

    protected TransportService_TransportServicePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new TransportServiceImpl();
        String address = "http://localhost:8080/TransportServicePort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new TransportService_TransportServicePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
