
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ttu.idu0080.orderservice.ordershipments;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-05-13T14:36:18.108+03:00
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "OrderShipmentServiceService",
                      portName = "OrderShipmentServicePort",
                      targetNamespace = "http://server.order.idu0080.ttu/",
                      wsdlLocation = "file:/C:/Users/Random/workspace4test2/OrderService/src/order_shipments.wsdl",
                      endpointInterface = "ttu.idu0080.orderservice.ordershipments.OrderShipmentService")
                      
public class OrderShipmentServiceImpl implements OrderShipmentService {

    private static final Logger LOG = Logger.getLogger(OrderShipmentServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see ttu.idu0080.orderservice.ordershipments.OrderShipmentService#getOrderShipmentsByOrderIdRyhmName(int  orderId ,)java.lang.String  ryhmName )*
     */
    public java.util.List<ttu.idu0080.orderservice.ordershipments.OrderShipment> getOrderShipmentsByOrderIdRyhmName(int orderId,java.lang.String ryhmName) { 
        LOG.info("Executing operation getOrderShipmentsByOrderIdRyhmName");
        System.out.println(orderId);
        System.out.println(ryhmName);
        try {
            java.util.List<ttu.idu0080.orderservice.ordershipments.OrderShipment> _return = new java.util.ArrayList<ttu.idu0080.orderservice.ordershipments.OrderShipment>();
            ttu.idu0080.orderservice.ordershipments.OrderShipment _returnVal1 = new ttu.idu0080.orderservice.ordershipments.OrderShipment();
            _returnVal1.setApproxDeliveryDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-05-13T14:36:18.141+03:00"));
            _returnVal1.setCourierName("CourierName1420291314");
            _returnVal1.setOrder(1872804451);
            _returnVal1.setOrderShipment(864185966);
            _returnVal1.setRyhmName("RyhmName-331487150");
            _returnVal1.setShippingPrice(0.280517383978815);
            _returnVal1.setTrackingNumber("TrackingNumber598072240");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.orderservice.ordershipments.OrderShipmentService#insertOrderShipment(int  orderId ,)java.lang.String  ryhmName ,)java.lang.String  trackingNumber ,)java.lang.String  courierName ,)javax.xml.datatype.XMLGregorianCalendar  approxDeliveryDate ,)double  shippingPrice )*
     */
    public int insertOrderShipment(int orderId,java.lang.String ryhmName,java.lang.String trackingNumber,java.lang.String courierName,javax.xml.datatype.XMLGregorianCalendar approxDeliveryDate,double shippingPrice) { 
        LOG.info("Executing operation insertOrderShipment");
        System.out.println(orderId);
        System.out.println(ryhmName);
        System.out.println(trackingNumber);
        System.out.println(courierName);
        System.out.println(approxDeliveryDate);
        System.out.println(shippingPrice);
        try {
            int _return = -1308037197;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
