
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ttu.idu0080.transport.orderclient;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-05-15T08:29:17.132+03:00
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "OrderServiceService",
                      portName = "OrderServicePort",
                      targetNamespace = "http://server.order.idu0080.ttu/",
                      wsdlLocation = "http://localhost:8080/OrderService/services/OrderServicePort?wsdl",
                      endpointInterface = "ttu.idu0080.transport.orderclient.OrderService")
                      
public class OrderServiceImpl implements OrderService {

    private static final Logger LOG = Logger.getLogger(OrderServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see ttu.idu0080.transport.orderclient.OrderService#getOrdersByCustomerId(int  customerId )*
     */
    public java.util.List<ttu.idu0080.transport.orderclient.Order> getOrdersByCustomerId(int customerId) { 
        LOG.info("Executing operation getOrdersByCustomerId");
        System.out.println(customerId);
        try {
            java.util.List<ttu.idu0080.transport.orderclient.Order> _return = new java.util.ArrayList<ttu.idu0080.transport.orderclient.Order>();
            ttu.idu0080.transport.orderclient.Order _returnVal1 = new ttu.idu0080.transport.orderclient.Order();
            ttu.idu0080.transport.orderclient.Customer _returnVal1Customer = new ttu.idu0080.transport.orderclient.Customer();
            java.util.List<ttu.idu0080.transport.orderclient.Address> _returnVal1CustomerAddresses = new java.util.ArrayList<ttu.idu0080.transport.orderclient.Address>();
            _returnVal1Customer.getAddresses().addAll(_returnVal1CustomerAddresses);
            _returnVal1Customer.setCustomer(-1138502517);
            _returnVal1Customer.setFirstName("FirstName-945301343");
            _returnVal1Customer.setLastName("LastName-1557721072");
            _returnVal1.setCustomer(_returnVal1Customer);
            _returnVal1.setOrderId(-1571785528);
            java.util.List<ttu.idu0080.transport.orderclient.OrderProduct> _returnVal1OrderProducts = new java.util.ArrayList<ttu.idu0080.transport.orderclient.OrderProduct>();
            ttu.idu0080.transport.orderclient.OrderProduct _returnVal1OrderProductsVal1 = new ttu.idu0080.transport.orderclient.OrderProduct();
            _returnVal1OrderProductsVal1.setOrderProduct(1521924620);
            _returnVal1OrderProductsVal1.setPrice(0.969351f);
            _returnVal1OrderProductsVal1.setPriceTotal(0.6617339f);
            _returnVal1OrderProductsVal1.setProductCount(1031060506);
            _returnVal1OrderProductsVal1.setProductName("ProductName891277935");
            _returnVal1OrderProducts.add(_returnVal1OrderProductsVal1);
            _returnVal1.getOrderProducts().addAll(_returnVal1OrderProducts);
            _returnVal1.setPriceTotal(0.05944568f);
            ttu.idu0080.transport.orderclient.Seller _returnVal1Seller = new ttu.idu0080.transport.orderclient.Seller();
            java.util.List<ttu.idu0080.transport.orderclient.EntAddress> _returnVal1SellerAddresses = new java.util.ArrayList<ttu.idu0080.transport.orderclient.EntAddress>();
            _returnVal1Seller.getAddresses().addAll(_returnVal1SellerAddresses);
            _returnVal1Seller.setEnterprise(-193915684);
            _returnVal1Seller.setName("Name1735389231");
            _returnVal1.setSeller(_returnVal1Seller);
            ttu.idu0080.transport.orderclient.Address _returnVal1ShippingAddress = new ttu.idu0080.transport.orderclient.Address();
            _returnVal1ShippingAddress.setAddress(1236441083);
            _returnVal1ShippingAddress.setCountry("Country199195133");
            _returnVal1ShippingAddress.setCounty("County-1647742278");
            _returnVal1ShippingAddress.setStreetAddress("StreetAddress-1761271672");
            _returnVal1ShippingAddress.setTownVillage("TownVillage2138850872");
            _returnVal1ShippingAddress.setZipcode("Zipcode-2109064236");
            _returnVal1.setShippingAddress(_returnVal1ShippingAddress);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.transport.orderclient.OrderService#getAllOrders(*
     */
    public java.util.List<ttu.idu0080.transport.orderclient.Order> getAllOrders() { 
        LOG.info("Executing operation getAllOrders");
        try {
            java.util.List<ttu.idu0080.transport.orderclient.Order> _return = new java.util.ArrayList<ttu.idu0080.transport.orderclient.Order>();
            ttu.idu0080.transport.orderclient.Order _returnVal1 = new ttu.idu0080.transport.orderclient.Order();
            ttu.idu0080.transport.orderclient.Customer _returnVal1Customer = new ttu.idu0080.transport.orderclient.Customer();
            java.util.List<ttu.idu0080.transport.orderclient.Address> _returnVal1CustomerAddresses = new java.util.ArrayList<ttu.idu0080.transport.orderclient.Address>();
            _returnVal1Customer.getAddresses().addAll(_returnVal1CustomerAddresses);
            _returnVal1Customer.setCustomer(-347422358);
            _returnVal1Customer.setFirstName("FirstName-164642071");
            _returnVal1Customer.setLastName("LastName-770489866");
            _returnVal1.setCustomer(_returnVal1Customer);
            _returnVal1.setOrderId(-163806914);
            java.util.List<ttu.idu0080.transport.orderclient.OrderProduct> _returnVal1OrderProducts = new java.util.ArrayList<ttu.idu0080.transport.orderclient.OrderProduct>();
            ttu.idu0080.transport.orderclient.OrderProduct _returnVal1OrderProductsVal1 = new ttu.idu0080.transport.orderclient.OrderProduct();
            _returnVal1OrderProductsVal1.setOrderProduct(851838159);
            _returnVal1OrderProductsVal1.setPrice(0.17021644f);
            _returnVal1OrderProductsVal1.setPriceTotal(0.9322279f);
            _returnVal1OrderProductsVal1.setProductCount(-177867000);
            _returnVal1OrderProductsVal1.setProductName("ProductName1220397520");
            _returnVal1OrderProducts.add(_returnVal1OrderProductsVal1);
            _returnVal1.getOrderProducts().addAll(_returnVal1OrderProducts);
            _returnVal1.setPriceTotal(0.303851f);
            ttu.idu0080.transport.orderclient.Seller _returnVal1Seller = new ttu.idu0080.transport.orderclient.Seller();
            java.util.List<ttu.idu0080.transport.orderclient.EntAddress> _returnVal1SellerAddresses = new java.util.ArrayList<ttu.idu0080.transport.orderclient.EntAddress>();
            _returnVal1Seller.getAddresses().addAll(_returnVal1SellerAddresses);
            _returnVal1Seller.setEnterprise(803757438);
            _returnVal1Seller.setName("Name-2057079700");
            _returnVal1.setSeller(_returnVal1Seller);
            ttu.idu0080.transport.orderclient.Address _returnVal1ShippingAddress = new ttu.idu0080.transport.orderclient.Address();
            _returnVal1ShippingAddress.setAddress(-2111108991);
            _returnVal1ShippingAddress.setCountry("Country949052869");
            _returnVal1ShippingAddress.setCounty("County639951095");
            _returnVal1ShippingAddress.setStreetAddress("StreetAddress-1971425662");
            _returnVal1ShippingAddress.setTownVillage("TownVillage2091615365");
            _returnVal1ShippingAddress.setZipcode("Zipcode123433008");
            _returnVal1.setShippingAddress(_returnVal1ShippingAddress);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.transport.orderclient.OrderService#getOrdersByOrderId(int  orderId )*
     */
    public ttu.idu0080.transport.orderclient.Order getOrdersByOrderId(int orderId) { 
        LOG.info("Executing operation getOrdersByOrderId");
        System.out.println(orderId);
        try {
            ttu.idu0080.transport.orderclient.Order _return = new ttu.idu0080.transport.orderclient.Order();
            ttu.idu0080.transport.orderclient.Customer _returnCustomer = new ttu.idu0080.transport.orderclient.Customer();
            java.util.List<ttu.idu0080.transport.orderclient.Address> _returnCustomerAddresses = new java.util.ArrayList<ttu.idu0080.transport.orderclient.Address>();
            ttu.idu0080.transport.orderclient.Address _returnCustomerAddressesVal1 = new ttu.idu0080.transport.orderclient.Address();
            _returnCustomerAddressesVal1.setAddress(-141880552);
            _returnCustomerAddressesVal1.setCountry("Country1781247733");
            _returnCustomerAddressesVal1.setCounty("County-1400156243");
            _returnCustomerAddressesVal1.setStreetAddress("StreetAddress-1042138626");
            _returnCustomerAddressesVal1.setTownVillage("TownVillage1320028183");
            _returnCustomerAddressesVal1.setZipcode("Zipcode-298696198");
            _returnCustomerAddresses.add(_returnCustomerAddressesVal1);
            _returnCustomer.getAddresses().addAll(_returnCustomerAddresses);
            _returnCustomer.setCustomer(51466980);
            _returnCustomer.setFirstName("FirstName-672185955");
            _returnCustomer.setLastName("LastName851569356");
            _return.setCustomer(_returnCustomer);
            _return.setOrderId(511627134);
            java.util.List<ttu.idu0080.transport.orderclient.OrderProduct> _returnOrderProducts = new java.util.ArrayList<ttu.idu0080.transport.orderclient.OrderProduct>();
            ttu.idu0080.transport.orderclient.OrderProduct _returnOrderProductsVal1 = new ttu.idu0080.transport.orderclient.OrderProduct();
            _returnOrderProductsVal1.setOrderProduct(-477036209);
            _returnOrderProductsVal1.setPrice(0.7422822f);
            _returnOrderProductsVal1.setPriceTotal(0.7279948f);
            _returnOrderProductsVal1.setProductCount(-1489579106);
            _returnOrderProductsVal1.setProductName("ProductName-2126407248");
            _returnOrderProducts.add(_returnOrderProductsVal1);
            _return.getOrderProducts().addAll(_returnOrderProducts);
            _return.setPriceTotal(0.2772773f);
            ttu.idu0080.transport.orderclient.Seller _returnSeller = new ttu.idu0080.transport.orderclient.Seller();
            java.util.List<ttu.idu0080.transport.orderclient.EntAddress> _returnSellerAddresses = new java.util.ArrayList<ttu.idu0080.transport.orderclient.EntAddress>();
            ttu.idu0080.transport.orderclient.EntAddress _returnSellerAddressesVal1 = new ttu.idu0080.transport.orderclient.EntAddress();
            _returnSellerAddressesVal1.setAddress(-959203159);
            _returnSellerAddressesVal1.setCountry("Country1642228316");
            _returnSellerAddressesVal1.setCounty("County-1258448373");
            _returnSellerAddressesVal1.setStreetAddress("StreetAddress2072941291");
            _returnSellerAddressesVal1.setTownVillage("TownVillage-675620925");
            _returnSellerAddressesVal1.setZipcode("Zipcode-1564826994");
            _returnSellerAddresses.add(_returnSellerAddressesVal1);
            _returnSeller.getAddresses().addAll(_returnSellerAddresses);
            _returnSeller.setEnterprise(1460881803);
            _returnSeller.setName("Name172361039");
            _return.setSeller(_returnSeller);
            ttu.idu0080.transport.orderclient.Address _returnShippingAddress = new ttu.idu0080.transport.orderclient.Address();
            _returnShippingAddress.setAddress(207329599);
            _returnShippingAddress.setCountry("Country429231129");
            _returnShippingAddress.setCounty("County1215921317");
            _returnShippingAddress.setStreetAddress("StreetAddress-1538203520");
            _returnShippingAddress.setTownVillage("TownVillage-679660400");
            _returnShippingAddress.setZipcode("Zipcode-137857697");
            _return.setShippingAddress(_returnShippingAddress);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.transport.orderclient.OrderService#getAllCouriers(*
     */
    public java.util.List<ttu.idu0080.transport.orderclient.Courier> getAllCouriers() { 
        LOG.info("Executing operation getAllCouriers");
        try {
            java.util.List<ttu.idu0080.transport.orderclient.Courier> _return = new java.util.ArrayList<ttu.idu0080.transport.orderclient.Courier>();
            ttu.idu0080.transport.orderclient.Courier _returnVal1 = new ttu.idu0080.transport.orderclient.Courier();
            java.util.List<ttu.idu0080.transport.orderclient.EntAddress> _returnVal1Addresses = new java.util.ArrayList<ttu.idu0080.transport.orderclient.EntAddress>();
            ttu.idu0080.transport.orderclient.EntAddress _returnVal1AddressesVal1 = new ttu.idu0080.transport.orderclient.EntAddress();
            _returnVal1AddressesVal1.setAddress(373946237);
            _returnVal1AddressesVal1.setCountry("Country-113794198");
            _returnVal1AddressesVal1.setCounty("County166723107");
            _returnVal1AddressesVal1.setStreetAddress("StreetAddress-454292491");
            _returnVal1AddressesVal1.setTownVillage("TownVillage-1533734263");
            _returnVal1AddressesVal1.setZipcode("Zipcode-1743464071");
            _returnVal1Addresses.add(_returnVal1AddressesVal1);
            _returnVal1.getAddresses().addAll(_returnVal1Addresses);
            _returnVal1.setEnterprise(894064287);
            _returnVal1.setName("Name1391809689");
            _returnVal1.setPercentFromOrder(-1732737676);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.transport.orderclient.OrderService#getCourierById(int  courierId )*
     */
    public ttu.idu0080.transport.orderclient.Courier getCourierById(int courierId) { 
        LOG.info("Executing operation getCourierById");
        System.out.println(courierId);
        try {
            ttu.idu0080.transport.orderclient.Courier _return = new ttu.idu0080.transport.orderclient.Courier();
            java.util.List<ttu.idu0080.transport.orderclient.EntAddress> _returnAddresses = new java.util.ArrayList<ttu.idu0080.transport.orderclient.EntAddress>();
            ttu.idu0080.transport.orderclient.EntAddress _returnAddressesVal1 = new ttu.idu0080.transport.orderclient.EntAddress();
            _returnAddressesVal1.setAddress(-217950793);
            _returnAddressesVal1.setCountry("Country317639278");
            _returnAddressesVal1.setCounty("County1641131618");
            _returnAddressesVal1.setStreetAddress("StreetAddress2040364100");
            _returnAddressesVal1.setTownVillage("TownVillage-1783198951");
            _returnAddressesVal1.setZipcode("Zipcode1742087548");
            _returnAddresses.add(_returnAddressesVal1);
            _return.getAddresses().addAll(_returnAddresses);
            _return.setEnterprise(-1696377543);
            _return.setName("Name1004559038");
            _return.setPercentFromOrder(1680774677);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.transport.orderclient.OrderService#getAllProducts(*
     */
    public java.util.List<ttu.idu0080.transport.orderclient.Product> getAllProducts() { 
        LOG.info("Executing operation getAllProducts");
        try {
            java.util.List<ttu.idu0080.transport.orderclient.Product> _return = new java.util.ArrayList<ttu.idu0080.transport.orderclient.Product>();
            ttu.idu0080.transport.orderclient.Product _returnVal1 = new ttu.idu0080.transport.orderclient.Product();
            _returnVal1.setDescription("Description-1543471298");
            _returnVal1.setEshopPrice(0.9399275f);
            _returnVal1.setName("Name1663488520");
            _returnVal1.setProduct(1324796792);
            _returnVal1.setProductCode("ProductCode1495040758");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
