
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ttu.idu0080.transport.couriers;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-05-14T14:57:24.073+03:00
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "CourierServiceService",
                      portName = "CourierServicePort",
                      targetNamespace = "http://server.order.idu0080.ttu/",
                      wsdlLocation = "http://localhost:8080/OrderService/services/CourierServicePort?wsdl",
                      endpointInterface = "ttu.idu0080.transport.couriers.CourierService")
                      
public class CourierServiceImpl implements CourierService {

    private static final Logger LOG = Logger.getLogger(CourierServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see ttu.idu0080.transport.couriers.CourierService#getCouriersByAddress(java.lang.String  country ,)java.lang.String  county )*
     */
    public java.util.List<ttu.idu0080.transport.couriers.Courier> getCouriersByAddress(java.lang.String country,java.lang.String county) { 
        LOG.info("Executing operation getCouriersByAddress");
        System.out.println(country);
        System.out.println(county);
        try {
            java.util.List<ttu.idu0080.transport.couriers.Courier> _return = new java.util.ArrayList<ttu.idu0080.transport.couriers.Courier>();
            ttu.idu0080.transport.couriers.Courier _returnVal1 = new ttu.idu0080.transport.couriers.Courier();
            java.util.List<ttu.idu0080.transport.couriers.EntAddress> _returnVal1Addresses = new java.util.ArrayList<ttu.idu0080.transport.couriers.EntAddress>();
            ttu.idu0080.transport.couriers.EntAddress _returnVal1AddressesVal1 = new ttu.idu0080.transport.couriers.EntAddress();
            _returnVal1AddressesVal1.setAddress(338460327);
            _returnVal1AddressesVal1.setCountry("Country-511833091");
            _returnVal1AddressesVal1.setCounty("County-940226239");
            _returnVal1AddressesVal1.setStreetAddress("StreetAddress552509504");
            _returnVal1AddressesVal1.setTownVillage("TownVillage1695683502");
            _returnVal1AddressesVal1.setZipcode("Zipcode-1573135616");
            _returnVal1Addresses.add(_returnVal1AddressesVal1);
            _returnVal1.getAddresses().addAll(_returnVal1Addresses);
            _returnVal1.setEnterprise(1105165169);
            _returnVal1.setName("Name-1171884011");
            _returnVal1.setPercentFromOrder(-763547762);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.transport.couriers.CourierService#getCourierById(int  courierId )*
     */
    public ttu.idu0080.transport.couriers.Courier getCourierById(int courierId) { 
        LOG.info("Executing operation getCourierById");
        System.out.println(courierId);
        try {
            ttu.idu0080.transport.couriers.Courier _return = new ttu.idu0080.transport.couriers.Courier();
            java.util.List<ttu.idu0080.transport.couriers.EntAddress> _returnAddresses = new java.util.ArrayList<ttu.idu0080.transport.couriers.EntAddress>();
            ttu.idu0080.transport.couriers.EntAddress _returnAddressesVal1 = new ttu.idu0080.transport.couriers.EntAddress();
            _returnAddressesVal1.setAddress(1828135123);
            _returnAddressesVal1.setCountry("Country1148553751");
            _returnAddressesVal1.setCounty("County-2047256584");
            _returnAddressesVal1.setStreetAddress("StreetAddress1960257623");
            _returnAddressesVal1.setTownVillage("TownVillage-11976016");
            _returnAddressesVal1.setZipcode("Zipcode-2141066821");
            _returnAddresses.add(_returnAddressesVal1);
            _return.getAddresses().addAll(_returnAddresses);
            _return.setEnterprise(-1977509932);
            _return.setName("Name-2079547933");
            _return.setPercentFromOrder(1645672854);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.transport.couriers.CourierService#getAllCouriers(*
     */
    public java.util.List<ttu.idu0080.transport.couriers.Courier> getAllCouriers() { 
        LOG.info("Executing operation getAllCouriers");
        try {
            java.util.List<ttu.idu0080.transport.couriers.Courier> _return = new java.util.ArrayList<ttu.idu0080.transport.couriers.Courier>();
            ttu.idu0080.transport.couriers.Courier _returnVal1 = new ttu.idu0080.transport.couriers.Courier();
            java.util.List<ttu.idu0080.transport.couriers.EntAddress> _returnVal1Addresses = new java.util.ArrayList<ttu.idu0080.transport.couriers.EntAddress>();
            ttu.idu0080.transport.couriers.EntAddress _returnVal1AddressesVal1 = new ttu.idu0080.transport.couriers.EntAddress();
            _returnVal1AddressesVal1.setAddress(740435079);
            _returnVal1AddressesVal1.setCountry("Country1371310890");
            _returnVal1AddressesVal1.setCounty("County-1941019114");
            _returnVal1AddressesVal1.setStreetAddress("StreetAddress2057962299");
            _returnVal1AddressesVal1.setTownVillage("TownVillage-1713214931");
            _returnVal1AddressesVal1.setZipcode("Zipcode1564319011");
            _returnVal1Addresses.add(_returnVal1AddressesVal1);
            _returnVal1.getAddresses().addAll(_returnVal1Addresses);
            _returnVal1.setEnterprise(-1103201946);
            _returnVal1.setName("Name201354816");
            _returnVal1.setPercentFromOrder(1554496008);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
