package ttu.idu0080.orderservice.products;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-05-13T14:29:11.398+03:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://server.order.idu0080.ttu/", name = "ProductService")
@XmlSeeAlso({ObjectFactory.class})
public interface ProductService {

    @WebMethod
    @Action(input = "http://server.order.idu0080.ttu/ProductService/getAllProductsRequest", output = "http://server.order.idu0080.ttu/ProductService/getAllProductsResponse")
    @RequestWrapper(localName = "getAllProducts", targetNamespace = "http://server.order.idu0080.ttu/", className = "ttu.idu0080.orderservice.products.GetAllProducts")
    @ResponseWrapper(localName = "getAllProductsResponse", targetNamespace = "http://server.order.idu0080.ttu/", className = "ttu.idu0080.orderservice.products.GetAllProductsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ttu.idu0080.orderservice.products.Product> getAllProducts();
}
